### ISSUE TITLE
Edit automation name

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#2463]
**Describe the feature request**
It is possible to edit the names of apps, datasources and pages, but not of automations. It would be nice if that would also be possible.

### Tasks

- [x] Add a context menu item called `Edit` to edit the name of an automation. 
- [x] Add an UpdateAutomationModal with a single input, like the UpdateDatasourceModal and a title `Edit automation`
- [x] Clicking the Save button will update the automation name.

**Screenshots**
<img width="394" alt="image" src="https://user-images.githubusercontent.com/1907152/130782782-2e5ce150-60d8-4ddd-bba1-60601a05b025.png">
