### ISSUE TITLE
Settings Modal Todo

### ISSUE THREAD

**Issue by kevmodrome** [Budibase/budibase#395]
Decided to push the settings panel when not quite done yet since there was no current way to add/edit users. There are still some things that need work:

- [x] Make it more visually inline with the designs
- [x] Possible to update app name/description
- [ ] Tests for updating app name/description
- [x] Ability to delete apps
- [ ] Add unit tests for editing users
- [ ] Change integration test to use the new way of adding users and also add edit user test
- [x] Ability to add sendgrid API key
- [x] Ability to add budibase API key

For the API Keys, these need to be appended to the file at ~/.budibase/.env and set in code:
```js
process.env.SENDGRID_API_KEY
process.env.BUDIBASE_API_KEY
```
