### ISSUE TITLE
Custom Components and Datasources: Documentation

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#6958]
### COS
There are several parts to the documentation required for components and datasources. The main tasks are:

#### Schema Definition
Defining the exhaustive schema in tabular format for 
- [x] `schema.json`, 
- [ ] `manifest.json` 
- [x] CLI commands and flags
- [ ] SDK/OpenAPI

#### End to End Tutorials and examples
Creating an end to end tutorial of how to:

- [x] Create a component or datasource from CLI
- [ ] General skeleton explanation, rollup, .github, jest (datasource)
- [x] Development experience, watching, environment variable for server
- [ ] Using your datasource or component in the builder and editing the props
- [ ] Examples/tutorials for component/datasources and links to example repos

#### Plugin Management
- [ ] Any Caveats
- [x] Initial setup to use plugins on both self host and in cloud
- [x] Detail around all the different types of plugin sources and how you pull from them
- [x] Creating plugins
- [x] Updating plugins
- [x] Deleting plugins
- [ ] How to contribute a plugin and include it on the new budibase plugins repo

**Comment by joebudi** [comment]
@shogunpurple Should we inform users about the plugin repo in the docs?

**Comment by shogunpurple** [comment]
Makes sense @joebudi - will add
